---
- name: Generate hosts
  tags: hosts
  hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Add node
    add_host:
      name: "{{host_prefix}}-node{{item}}"
      groups: hosts
      rax_flavor: performance1-4
      iface:
        tunnel_dev: eth2
        tunnel_ip: 172.20.{{cluster_id}}.{{item}}/24
        tunnel_id: "{{cluster_id}}"
        tunnel_name: vxlan{{cluster_id}}
    with_sequence: count={{host_count}}
