---
- name: Ensure xfsprogs package is installed
  apt:
    pkg: "xfsprogs"
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Create LVs for Swift
  lvol:
    vg: lxc 
    lv: "{{ item }}"
    size: 10G
  with_items:
    - swift1
    - swift2
    - swift3
    - swift4
    - swift5

- name: Create swift mount dirs
  file:
    state: directory
    path: "/mnt/{{ item }}"
  with_items:
    - swift1
    - swift2
    - swift3
    - swift4
    - swift5

- name: mkfs.xfs swift partitions
  shell: "xfs_info /dev/lxc/{{ item }} || mkfs.xfs -f /dev/lxc/{{ item }}"
  with_items:
    - swift1
    - swift2
    - swift3
    - swift4
    - swift5

- name: Mount swift partitions
  mount: 
    state: mounted
    fstype: xfs
    src: "/dev/lxc/{{ item }}"
    name: "/mnt/{{ item }}"
  with_items:
    - swift1
    - swift2
    - swift3
    - swift4
    - swift5

